### ISSUE TITLE
Apply license correctly

### ISSUE THREAD

**Issue by cagix** [KI-Vorlesung/kitest#2]
- Canan: CC BY-NC-SA (https://creativecommons.org/choose/: "This is not a Free Culture License")
- Carsten: MIT or CC BY-SA

---

- [x] Find an example of application of a mixed licence (Readme.md and Licence.md) ...
- [x] Add mixed licence to Github-Repo (`Readme.md`, `Licence.md`)

--- 

Add license statement plus cc-by-sa-4.0 logo to 
- [x] Github-Repo (`Readme.md`) and 
- [x] GH-Pages (`custom-footer.hml`), 
- [x] Extending the license statement to contributors

start from text/link from https://creativecommons.org/choose/

---

Also add footer on 
- [x] #90
- [x] videos (footer? summary on last frame? title frame?)

Regarding the slides there is a separate ticket now (#90). The video task will be automatically solved once there is some license hint on the slides ...

**Comment by cyildiz** [comment]
The licenses that are listed ready to choose from are: 
https://github.com/github/choosealicense.com/tree/gh-pages/_licenses

If a license is not listed, one can [request adding a license](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license), provided the license meets some requirements.
The CC-BY-NC-ND-4.0 has  an [SPDX identifier](https://spdx.org/licenses/CC-BY-NC-ND-4.0.html), but it is not listed in one of the "approved list of licenses".

Question: Use **CC-BY-SA-4.0** for whole repository?

**Comment by cyildiz** [comment]
In [this discussion](https://softwareengineering.stackexchange.com/questions/304874/declaring-multiple-licences-in-a-github-project) regarding the use of multiple licenses in one GitHub Project, an SPDX presentation is referenced, which says (on [Slide 13](https://events.static.linuxfound.org/sites/events/files/Introduction%20to%20SPDX-without%20graphics.pdf)):
**WITH**: Exceptions (apply an exception to the main license)
But it seems, this can only be used with some predefined [SPDX-exceptions](https://spdx.org/licenses/exceptions-index.html).

Meanwhile (as an example) in this [repository about misc-licenses](https://github.com/benlk/misc-licenses), the readme.md file contains a "is dual-licensed under" statement, one of which is the [Schrödinger License](https://github.com/benlk/misc-licenses/blob/master/schrodinger-license.md).

**Comment by cagix** [comment]
> Question: Use CC-BY-SA-4.0 for whole repository?

that seems reasonable 👍

**Comment by cagix** [comment]
> If a license is not listed, one can request adding a license, provided the license meets some requirements.

@cyildiz shall we do this, i.e. request adding cc-by-as-4.0?

**Comment by cyildiz** [comment]
There was a misunderstanding on my part:
the request for adding new licenses is for the list on choosealicense.com (cc-by-sa-4.0 is already in that list),
but this is not equal to the list of ready-to-choose-from license templates that appears when trying to add a "license.md" file to the repository.

Although cc-by-sa-4.0 is not listed in the ready-to-choose-from templates, if the corresponding license.md file is added to the root directory of the repository, the correct license is automatically detected and displayed on the main page of the repo
([example](https://github.com/jwasham/coding-interview-university)).

**Comment by cagix** [comment]
https://github.com/KI-Vorlesung/Lecture/commit/8bfbdad7f6a350a1c5b1bc93f64047ccb4aa508c added CC BY-SA 4.0

**Comment by cagix** [comment]
Besprechung 16.08.21: Wir ändern den Lizenz-Abschnitt im Readme: 

- [ ] die Jahreszahl wird entfernt
- [ ] statt dem "neuen" Logo (aus dem Beta-License-Chooser) wird das bisherige Logo (aus dem Standard-License-Chooser) verwendet

**Comment by cagix** [comment]
ok, umgesetzt wie per mail besprochen
