### ISSUE TITLE
Prüfungsfragen: Repo?

### ISSUE THREAD

**Issue by cagix** [KI-Vorlesung/kitest#23]
@cyildiz Brauchen wir für die Prüfungsfragen ein weiteres privates Repo oder nutzen wir das Repo für die Quizzes gleich mit?

**Comment by cyildiz** [comment]
Repo für Quizzes scheint mir  in Ordnung zu sein. Oder spricht etwas dagegen?
Wenn es etwas mehr isoliert und geschützt sein soll als die Quizfragen, könnte man eine eigene Repo vorziehen...

**Comment by cagix** [comment]
@cyildiz ok, dann machen wir das so und nehmen erstmal das quiz-repo.

dann sollten wir vielleicht aber nochmal über die strukturen nachdenken. ich hatte vorgeschlagen, für jede sitzung eine eigene datei zu nehmen. aber vielleicht wird das gar nicht so viel und es ist einfacher, alles jeweils in einer datei zu haben, also eine datei für quizzes und eine für prüfungsfragen? hmmm, irgendwie fühlt sich das noch nicht richtig an ...

**Comment by cyildiz** [comment]
Eine Datei pro Thema/Woche/Sitzung könnte einfacher zu verwalten sein (damit nichts durcheinanderkommt, und man ggfl. nicht zu lange herunterscrollen muss).
Falls 1-3 Dateien sich thematisch nahe sind, könnten diese in Zukunft eventuell zusammengeführt werden?

**Comment by cagix** [comment]
> Eine Datei pro Thema/Woche/Sitzung könnte einfacher zu verwalten sein (damit nichts durcheinanderkommt, und man ggfl. nicht zu lange herunterscrollen muss).

Man könnte evtl. alles unter einer Hauptüberschrift zusammenfassen. Also das, was aktuell im Test-Repo in der ersten Gliederungsstufe steht: Eine Datei für "Suche", eine für "CSP", eine für "MLP"? Oder wird das dann schon zu groß?

Wochenbasiert könnte schwierig sein, da wir ja die Wochenplanung separat von den Inhalten machen ... 

> Falls 1-3 Dateien sich thematisch nahe sind, könnten diese in Zukunft eventuell zusammengeführt werden?

Stimmt, das kann man natürlich auch immer tun :)

**Comment by cagix** [comment]
Habe einen entsprechenden Text in die "Beschreibung" des Quizzes-Repo geschrieben. Damit kann das Ticket hier zu :)
